### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by EukkMaru** [nemoVim/energyverse#1]
리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요리드미써주세요

**Comment by nemovim** [comment]
간단하게나마 작성해 드렸습니다!
